name: Hochzeit
favicon: null
layout_spectrum: 0.6250577818136662
typography_spectrum: 0.6392099084332585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3842781453859061
  lightness: 0.07813035231083632
  saturation: 0.6852815304882824
  rhythmicContrast: 0.000998122850432992
purpose: []
